exports.endpoints = {
    usernameAvailability: username =>    `minecraft/profile/name/${username}/available`,
    usernameToUUID: username =>          `users/profiles/minecraft/${username}`,
    changeName: username =>              `minecraft/profile/name/${username}`,
    UUIDtoProfile: uuid =>               `session/minecraft/profile/${uuid}`,
    resetSkin:                           `minecraft/profile/skins/active`,
    cape:                                `minecraft/profile/capes/active`,
    nameChangeEligibility:               `minecraft/profile/namechange`,
    usernameHistory: uuid =>             `user/profile/${uuid}/names`,
    changeSkin:                          `minecraft/profile/skins`,
    redeemVoucher: code =>               `productvoucher/${code}`,
    UUIDtoUsername: uuid =>              `user/profile/${uuid}`,
    createProfile:                       `minecraft/profile`,
    changePassword:                      `users/password`,
    userInfo:                            `user`,
}